name: Deploy Frontend to S3.

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2



      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ./wisdom-war  # Set working directory
  
      - name: Build the project
        run: npm run build
        working-directory: ./wisdom-war  # Set working directory

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Debug AWS credentials
        run: |
              echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
              echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
              echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"

      - name: Sync files to my S3 bucket
        run:  aws s3 sync "./wisdom-war/dist" s3://wisdom-wars

      


        




  
